### ISSUE TITLE
HealtCheckReply

### ISSUE THREAD

**Issue by tiero** [vulpemventures/vault-protobuf#2]
In the reply message we should include the current status for each micro-service we offer

**Comment by altafan** [comment]
what about this new health-check request/reply?
```
message HealthCheckRequest {}

message Service {
  string name = 1;
  string status = 2;
  string error = 3;
}

message HealthCheckReply {
  string status = 1;
  repeated Service services = 2;
}
```
* I would remove the `network` from the request in order to check every service, not just those you want to use
* I would add a macro status `serving|not serving` in the reply and a micro status `serving|not serving` with an optional error for every service we use (vault, regtest, blockcypher, esplora ATM)

**Comment by tiero** [comment]
ack
